version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
